import Head from "next/head"
import { useRouter } from "next/router"
import React from "react"
import ImageResults from "../components/ImageResults"
import SearchHeader from "../components/SearchHeader"
import SearchResults from "../components/SearchResults"
import Response from "../Response"

const Search = ({ data }) => {
  const router = useRouter()
  const { terms } = router.query
  return (
    <div>
      <Head>
        <title>{terms} - Google Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchHeader />
      {router.query.searchType === "image" ? (
        <ImageResults results={data} />
      ) : (
        <SearchResults results={data} />
      )}
    </div>
  )
}

export async function getServerSideProps(context) {
  const mockData = false
  const startIndex = context.query.start || 1
  const data = mockData
    ? Response
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${
          process.env.GOOGLE_API_KEY
        }&cx=${process.env.GOOGLE_CSE_ID}&q=${context.query.terms}${
          context.query.searchType && "&searchType=image"
        }&start=${startIndex}`
      ).then((res) => res.json())
  return {
    props: {
      data: data
    }
  }
}

export default Search
